#! /usr/bin/env python

class GenBankEntry:
	def __init__(self, data = None):
		self.mydict = {}
		self.data = data
		if self.data != None:
			with open(self.data, 'r') as f:
				for line in f.readlines():
					line.lstrip()
					if line.lstrip().startswith('ACCESSION'):
						self.mydict['Accession'] = line.split()[1]
					elif line.lstrip().startswith('ORGANISM'):
						self.mydict['Organism'] = line.split()[1] + line.split()[2]
					elif line.lstrip().startswith('VERSION'):
						self.mydict['GI'] = line.split()[2]
					elif line.lstrip().startswith('/gene'):
						self.mydict['Gene'] = line.split()[0]
	def __str__(self):
		return self.mydict['Organism']
	def display(self):
		print(self.mydict)
	def Motif(self, motif):
		origin = ''
		with open(self.data, 'r') as f:
			for line in f.readlines():
				if line.lstrip().startswith(('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')):
					origin = origin + str(line[10:])
		if motif in origin:
			print('TRUE')
		elif motif not in origin:
			print('FALSE')
	def gc(self):
		origin = ''
		with open(self.data, 'r') as f:
			for line in f.readlines():
				if line.lstrip().startswith(('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')):
					origin = origin + str(line[10:])
		G = origin.count('g')
		C = origin.count('c')
		gc_percentage = 100*((G + C)/len(origin))
		print(gc_percentage)

data = 'hw2_hla.gb.txt'
gb = GenBankEntry(data)
print('Sayal Guirales\n' + 'sguirale@uncc.edu\n')
print('Is motif AGC in my sequence?')
gb.Motif('agc')
print('Is motif AAAAAA in my sequence?') 
gb.Motif('aaaaaa')
print('GC Percentage is: ')
gb.gc()
