#! /usr/bin/env python3

from Bio import Entrez

def ncbi_download(search_term):
	#initial information
	Entrez.email = "sguirale@uncc.edu"
	
	searchHandle = Entrez.esearch(db="nucleotide", term=search_term, usehistory="y")
	searchResults = Entrez.read(searchHandle)
	searchHandle.close()
	webEnv = searchResults["WebEnv"]
	queryKey = searchResults["QueryKey"]
	batchSize = len(searchResults["IdList"])
	try:
		fetchHandle = Entrez.efetch(db="nucleotide", retmax=batchSize, rettype="fasta", retmode="text", webenv=webEnv, query_key=queryKey)
		data=fetchHandle.read()
		fetchHandle.close()
		return data
	except:
		None
	
search_term = input("Organism Name: ")
results = ncbi_download(search_term)
outfile = open("%s.fasta" % search_term, "w")
outfile.write(results)
